### ISSUE TITLE
ey Manuel

### ISSUE THREAD

**Issue by FrederikRogalski** [manniq31/libraryProgram#18]
Deine Menu funktion gibt mir beim eingabewert 34 -> 3 zurück... Das sollte ja eigentlich nicht sein :D

**Comment by manniq31** [comment]
Ja die nimmt nur ein Zeichen an weil ich dachte dass des für ein manü reicht aber wenn man mehr stellen eingibt is des natürlich blöd da muss ich noch nen check einbauen oder so
