### ISSUE TITLE
clearConsole:

### ISSUE THREAD

**Issue by FrederikRogalski** [manniq31/libraryProgram#32]
Ist das so erlaubt? Oder ist das nicht wieder so wie er behauptet hat eine nicht valide lösung weil es Betriebssystemabhängig ist...

**Comment by manniq31** [comment]
Es gibt ja aber für alle Betriebssysteme was.
Ich glaub problematisch is es nur wenn man was macht des nur auf windowss geht und des aber dann immer ausgeführt wird.
Aber sowas können wir ja nächste Vorlesung fragen.

**Comment by manniq31** [comment]
Er meinte ja es ist ok.
